services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: paymentsdb
      POSTGRES_USER: paymentsuser
      POSTGRES_PASSWORD: 5Nw5lw@8%d1RaW
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: