services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: paymentsdb
      POSTGRES_USER: paymentsuser
      POSTGRES_PASSWORD: 5Nw5lw@8%d1RaW
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5054:5054"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=paymentsdb;Username=paymentsuser;Password=5Nw5lw@8%d1RaW
    depends_on:
      - db

volumes:
  pgdata: