services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: paymentsdb
      POSTGRES_USER: paymentsuser
      POSTGRES_PASSWORD: 5Nw5lw@8%d1RaW
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paymentsuser -d paymentsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5054:5054"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=paymentsdb;Username=paymentsuser;Password=5Nw5lw@8%d1RaW
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata: