@host = http://localhost:5054
@profileId = 1
@paymentId = 17
@paymentContent = Petshop no iFood
@paymentDescription = 
@paymentAmount = -130.77
@paymentDate = 2025-09-12
@paymentCompleted = true

### Payments
GET {{host}}/api/v1/Payments
X-Profile-Id: {{profileId}}

###
GET {{host}}/api/v1/Payments/{{paymentId}}
X-Profile-Id: {{profileId}}

###
POST {{host}}/api/v1/Payments
Content-Type: application/json
X-Profile-Id: {{profileId}}

{
    "content": "{{paymentContent}}",
    "amount": {{paymentAmount}},
    "paymentDate": "{{paymentDate}}",
    "completed": {{paymentCompleted}}
}

###
PUT {{host}}/api/v1/Payments/{{paymentId}}
Content-Type: application/json
X-Profile-Id: {{profileId}}

{
    "amount": -80.71,
}

###
DELETE {{host}}/api/v1/Payments/{{paymentId}}
X-Profile-Id: {{profileId}}


### Profiles
GET {{host}}/api/v1/Profiles

###
POST {{host}}/api/v1/Profiles
Content-Type: application/json

{
    "name": "Adilson PJ"
}

###
DELETE {{host}}/api/v1/Profiles/{{profileId}}